apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartwish-backend
  labels:
    app: cartwish-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cartwish-backend
  template:
    metadata:
      labels:
        app: cartwish-backend
    spec:
      containers:
        - name: cartwish-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}