apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartwish-backend
  labels:
    app: cartwish-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cartwish-backend
  template:
    metadata:
      labels:
        app: cartwish-backend
    spec:
      containers:
        - name: cartwish-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi