apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartwish-backend
  labels:
    app: cartwish-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartwish-backend
  template:
    metadata:
      labels:
        app: cartwish-backend
    spec:
      containers:
        - name: cartwish-backend
          image: cartwish-backend:latest
          imagePullPolicy: Never

          ports:
            - name: http
              containerPort: 5000
              protocol: TCP

          envFrom:
            - secretRef:
                name: cartwish-backend-secret

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi